import { Rarity } from "../../gameConfig";

export interface DeathEffectDef {
    readonly type: "death_effect";
    name: string;
    rarity: Rarity;
    texture: string;
    particle: string;
    particleCount?: number;
    sound?: string;
    // For animated sprite effects (like black hole)
    isParticle?: boolean;
    sprites?: string[];
    animationSpeed?: number;
    animationScale?: number;
    // For particle effects with custom min/max particle counts
    minParticles?: number;
    maxParticles?: number;
    // Discord snowflake as a string - a JS number would lose precision.
    creatorDiscordId?: string;
}

export const DeathEffectDefs: Record<string, DeathEffectDef> = {
    death_none: {
        type: "death_effect",
        name: "No Effect",
        rarity: Rarity.Stock,
        texture: "loot-death-skull.img",
        particle: "deathSplash",
        particleCount: 0,
    },
    death_basic: {
        type: "death_effect",
        name: "Standard Death",
        rarity: Rarity.Stock,
        texture: "loot-death-basic-puff.img",
        particle: "deathSplash",
        particleCount: 10,
    },
    death_blood_explosion: {
        type: "death_effect",
        name: "Blood Explosion",
        rarity: Rarity.Epic,
        texture: "loot-blood-explosion.img",
        particle: "bloodExplosion",
        particleCount: 15,
        isParticle: false,
        sprites: [
            "part-death-blood-explosion-01.img",
            "part-death-blood-explosion-02.img",
            "part-death-blood-explosion-03.img",
            "part-death-blood-explosion-04.img",
            "part-death-blood-explosion-05.img",
            "part-death-blood-explosion-06.img",
            "part-death-blood-explosion-07.img",
            "part-death-blood-explosion-08.img",
            "part-death-blood-explosion-09.img",
            "part-death-blood-explosion-10.img",
        ],
        animationSpeed: 0.25,
        animationScale: 0.7,
    },
    death_confetti: {
        type: "death_effect",
        name: "Confetti",
        rarity: Rarity.Mythic,
        texture: "loot-death-confetti.img",
        particle: "confettiDeath",
        isParticle: true,
        minParticles: 150,
        maxParticles: 150,
    },
    death_sparkle: {
        type: "death_effect",
        name: "Mr Sparkles",
        rarity: Rarity.Mythic,
        texture: "loot-death-sparkly.img",
        particle: "sparklyDeath",
        isParticle: true,
        minParticles: 45,
        maxParticles: 55,
    },
    death_potato: {
        type: "death_effect",
        name: "Potato Blast",
        rarity: Rarity.Epic,
        texture: "loot-death-potato-blast.img",
        particle: "potatoBlastDeath",
        isParticle: true,
        minParticles: 45,
        maxParticles: 55,
    },
    death_toon_blast: {
        type: "death_effect",
        name: "Toon Blast",
        rarity: Rarity.Mythic,
        texture: "loot-death-explosive.img",
        particle: "explosiveDeath",
        isParticle: false,
        sprites: [
            "part-death-explosive-01.img",
            "part-death-explosive-02.img",
            "part-death-explosive-03.img",
            "part-death-explosive-04.img",
            "part-death-explosive-05.img",
            "part-death-explosive-06.img",
        ],
        animationSpeed: 0.2,
        animationScale: 1.3,
    },
    death_turkey_feathers: {
        type: "death_effect",
        name: "Turkey Feathers",
        rarity: Rarity.Rare,
        texture: "loot-perk-turkey_shoot.img",
        particle: "turkeyFeathersDeath",
        isParticle: true,
        minParticles: 30,
        maxParticles: 35,
    },
    death_cupid: {
        type: "death_effect",
        name: "Cupid Hearts",
        rarity: Rarity.Rare,
        texture: "loot-perk-cupid.img",
        particle: "cupidDeath",
        isParticle: true,
        minParticles: 30,
        maxParticles: 35,
    },
    death_black_hole: {
        type: "death_effect",
        name: "Black Hole",
        rarity: Rarity.Epic,
        texture: "loot-black-hole.img",
        particle: "blackHoleDeath",
        particleCount: 15,
        isParticle: false,
        sprites: [
            "part-death-black-hole-09.img",
            "part-death-black-hole-08.img",
            "part-death-black-hole-07.img",
            "part-death-black-hole-06.img",
            "part-death-black-hole-05.img",
            "part-death-black-hole-04.img",
            "part-death-black-hole-03.img",
            "part-death-black-hole-02.img",
            "part-death-black-hole-01.img",
        ],
        animationSpeed: 0.15,
        animationScale: 1.2,
    },
    death_pixel_explosion: { // above death effects
        type: "death_effect",
        name: "Pixel Explosion",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Epic,
        texture: "loot-pixel-explosion.img",
        particle: "pixelExplosionDeath",
        isParticle: false,
        sprites: [
            "part-death-pixel-explosion-01.img",
            "part-death-pixel-explosion-02.img",
            "part-death-pixel-explosion-03.img",
            "part-death-pixel-explosion-04.img",
            "part-death-pixel-explosion-05.img",
            "part-death-pixel-explosion-06.img",
            "part-death-pixel-explosion-07.img",
            "part-death-pixel-explosion-08.img",
            "part-death-pixel-explosion-09.img",
            "part-death-pixel-explosion-10.img",
        ],
        animationSpeed: 0.15,
        animationScale: 0.65,
    },
    death_pulse: { // above death effects
        type: "death_effect",
        name: "Pulse Death",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Epic,
        texture: "loot-death-pulse.img",
        particle: "pulseDeath",
        isParticle: false,
        sprites: [
            "part-death-pulse-01.img",
            "part-death-pulse-02.img",
            "part-death-pulse-03.img",
            "part-death-pulse-04.img",
            "part-death-pulse-05.img",
            "part-death-pulse-06.img",
            "part-death-pulse-07.img",
            "part-death-pulse-08.img",
        ],
        animationSpeed: 0.20,
        animationScale: 2.2,
    },
    death_smoke: { // above death effects
        type: "death_effect",
        name: "Smoke Death",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Epic,
        texture: "loot-death-smoke.img",
        particle: "smokeDeath",
        isParticle: false,
        sprites: [
            "part-death-smoke-01.img",
            "part-death-smoke-02.img",
            "part-death-smoke-03.img",
            "part-death-smoke-04.img",
            "part-death-smoke-05.img",
            "part-death-smoke-06.img",
            "part-death-smoke-07.img",
            "part-death-smoke-08.img",
            "part-death-smoke-09.img",
            "part-death-smoke-10.img",
            "part-death-smoke-11.img",
        ],
        animationSpeed: 0.35,
        animationScale: 0.65,
    
    },
    death_magic_spark: {
        type: "death_effect",
        name: "Magic Sparks",
        rarity: Rarity.Mythic,
        texture: "loot-magic-spark.img",
        particle: "magicSparkDeath",
        isParticle: true,
        minParticles: 30,
        maxParticles: 35,
    },
    death_touhou: { // above death effects
        type: "death_effect",
        name: "Touhou Death",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-death-touhou.img",
        particle: "touhouDeath",
        isParticle: true,
        minParticles: 25,
        maxParticles: 30,
    },
    death_bubble: { // above death effects
        type: "death_effect",
        name: "Bubble Death",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-death-bubble.img",
        particle: "bubbleDeath",
        isParticle: true,
        minParticles: 25,
        maxParticles: 30,
    },
    death_shattered_glass: { // above death effects
        type: "death_effect",
        name: "Shattered Glass",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-death-shattered-glass.img",
        particle: "shatteredGlassDeath",
        isParticle: true,
        minParticles: 20,
        maxParticles: 25,
    },
    death_xp_orb: { // above death effects
        type: "death_effect",
        name: "XP Orb",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-death-xp-orb.img",
        particle: "xpOrbDeath",
        isParticle: true,
        minParticles: 10,
        maxParticles: 30,
    },
    death_alphabet_soup: { // above death effects
        type: "death_effect",
        name: "Alphabet Soup",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-death-alphabet-soup.img",
        particle: "alphabetSoupDeath",
        isParticle: true,
        minParticles: 30,
        maxParticles: 40,
    },
    death_drop_cellphone: { // above death effects
        type: "death_effect",
        name: "Drop Cellphone",
        creatorDiscordId: "1468016902650462313",
        rarity: Rarity.Mythic,
        texture: "loot-drop-cellphone.img",
        particle: "dropCellphoneDeath",
        isParticle: true,
        minParticles: 1,
        maxParticles: 1,
    },
    death_billionaire: {
        type: "death_effect",
        name: "Billionaire",
        rarity: Rarity.Mythic,
        texture: "loot-death-billionaire.img",
        particle: "billionaireDeath",
        isParticle: true,
        minParticles: 30,
        maxParticles: 35,
    },
};
